[urls]
# Proxy URLs for untrusted requests. Leave blank for no proxying.
proxy = []

[authentication]
# Token to authenticate with Discord.
discord_token = ""
# Token to get paying users from Patreon.
patreon_token = ""
# Token to POST the stats for the bot to Top.gg
top_gg_token = ""
# Token that Top.gg uses to send webhooked votes to Assyst.
top_gg_webhook_token = ""
# Port in which the top.gg webhook runs on.
top_gg_webhook_port = 3000

# Assyst database information.
[database]
host = ""
username = ""
password = ""
database = ""
port = 3000

[prefix]
# When the bot joins a new guild, this will be the default prefix.
default = "-"

[logging_webhooks]
panic = { token = "", id = 0 }
error = { token = "", id = 0 }
vote = { token = "", id = 0 }

[dev]
# These Discord user IDs have full control of the bot, including developer-only commands.
# Also grants max-tier premium access.
admin_users = []

# When working with a dev instance, set this to the prefix "override" value for that instance
# to prevent triggering the production instance and the development instance at the same time.
prefix_override = "¬"

# Use this for development instances to prevent the bot from attempting to process messages
# in bad-translator channels. Prevents conflicts with production instance.
disable_bad_translator_channels = false

# Use this to disable the bot from checking reminders. Again useful when working with a
# development instance to prevent conflicts.
disable_reminder_check = false

# Use this to top the bot from POSTing its guild and shard counts to Top.gg. 
# Useful for development instances.
disable_bot_list_posting = false
