######
# NOTE: If using Patreon, you must create a `.patreon_refresh` file at the project root (i.e., same directory as this file).
# This file should have you Patreon refresh token in it as a raw string.
# If not using Patreon, you can safely exclude this file. However, you should also set `dev.disable_patreon_synchronisation` to true.
######

[urls]
# Proxy URLs for untrusted requests. Leave blank for no proxying.
proxy = []
# URL for Filer, the Assyst CDN.
filer = ""
# Bad translation URL.
bad_translation = ""

[authentication]
# Token to authenticate with Discord.
discord_token = ""
# Token to get paying users from Patreon.
patreon_token = ""
# Token to POST the stats for the bot to Top.gg
top_gg_token = ""
# Token that Top.gg uses to send webhooked votes to Assyst.
top_gg_webhook_token = ""
# Port in which the top.gg webhook runs on.
top_gg_webhook_port = 3000
# Authentication key for Filer, the Assyst CDN.
filer_key = ""
# Authentication key for NotSoAPI, for audio identification.
notsoapi = ""

# Assyst database information.
[database]
host = ""
username = ""
password = ""
database = ""
port = 3000

[prefix]
# When the bot joins a new guild, this will be the default prefix.
default = "-"

[logging_webhooks]
panic = { token = "", id = 0 }
error = { token = "", id = 0 }
vote = { token = "", id = 0 }
# Whether to use the webhooks on vote, panic, and error.
enable_webhooks = true

# Entitlements are the subscriptions for the app within Discord. You can probably leave these zeroed and the system will ignore them.
[entitlements]
tier_1_entitlement_id = 0
tier_2_entitlement_id = 0
tier_3_entitlement_id = 0
tier_4_entitlement_id = 0

[dev]
# These Discord user IDs have full control of the bot, including developer-only commands.
# Also grants max-tier premium access.
admin_users = []

# When working with a dev instance, set this to the prefix "override" value for that instance
# to prevent triggering the production instance and the development instance at the same time.
prefix_override = "¬"

# Use this for development instances to prevent the bot from attempting to process messages
# in bad-translator channels. Prevents conflicts with production instance.
disable_bad_translator_channels = false

# Use this to disable the bot from checking reminders. Again useful when working with a
# development instance to prevent conflicts.
disable_reminder_check = false

# Use this to top the bot from POSTing its guild and shard counts to Top.gg. 
# Useful for development instances.
disable_bot_list_posting = false

# Disables loading patrons from Patreon.
disable_patreon_synchronisation = false

# Whether to send the 'dev message' (see below)
dev_message = false

# For development instances, send a message when this guild is present in a READY packet.
dev_guild = 0

# The channel to send the dev message in.
dev_channel = 0

# Override the path to the Flux executable. Useful when doing dev work on Flux. Leave blank for default.
flux_executable_path_override = ""
