[package]
name = "assyst-slash-client"
version = "0.1.0"
edition = "2021"

[dependencies]
twilight-http = "0.15.4"
serde = { version = "1.0.190", features = ["derive"] }
tokio = { version = "1.33.0", features = ["full"] }
twilight-gateway = "0.15.4"
twilight-model = "0.15.4"
anyhow = "1.0.75"
