[package]
name = "assyst-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.34.0", features = ["full"] }
tracing = "0.1.37"
assyst-common = { path = "../assyst-common" }
assyst-database = { path = "../assyst-database" }
assyst-webserver = { path = "../assyst-webserver" }
twilight-gateway = { git = "https://github.com/Jacherr/twilight.git", branch = "main" }
twilight-model = { git = "https://github.com/Jacherr/twilight.git", branch = "main" }
twilight-http = { git = "https://github.com/Jacherr/twilight.git", branch = "main" }
anyhow = "1.0.75"
jemallocator = "0.5.4"
tracing-subscriber = { version = "0.3.16", features = ["time", "env-filter"] }
time = { version = "0.3.31", features = ["macros"] }
prometheus = "0.13.3"
lazy_static = "1.4.0"
async-trait = "0.1.77"
assyst-proc-macro = { path = "../assyst-proc-macro" }
bytes = "1.5.0"
serde = "1.0.196"
reqwest = { version = "0.11.24", features = ["json", "stream"] }
emoji = { git = "https://github.com/Jacherr/emoji-rs/", package = "emoji" }
url = "2.5.0"
futures-util = "0.3.30"
serde_json = "1.0.113"
moka = { version = "0.12.3", features = ["sync"] }
human_bytes = { version = "0.4", default-features = false }
shared = { git = "https://github.com/jacherr/wsi-shared" }
bincode = "1.3.3"
