[package]
name = "assyst-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.34.0", features = ["full"] }
tracing = "0.1.37"
assyst-common = { path = "../assyst-common" }
assyst-database = { path = "../assyst-database" }
twilight-gateway = { git = "https://github.com/Jacherr/twilight.git", branch = "main" }
twilight-model = { git = "https://github.com/Jacherr/twilight.git", branch = "main" }
twilight-http = { git = "https://github.com/Jacherr/twilight.git", branch = "main" }
anyhow = "1.0.75"
jemallocator = "0.5.4"
